### ISSUE TITLE
Sony firmware(issue?)

### ISSUE THREAD

**Issue by dymex0** [ma1co/fwtool.py#1]
Hey. Can it be modified to extract Sony action cam firmware? I tried extract HDR AZ1 firmware (.dat), but it gives me error
 ```
>fwtool.exe FirmwareData_Update_HDRAZ1V101.dat fwtool2
=== Extract encrypted FDAT record to 'fwtool2/FDAT_enc.bin' ===
Write chunk FDAT to 'fwtool2/FDAT_enc.bin' ... Done
=== Decrypt FDAT record to 'fwtool2/FDAT_dec.bin' ===
Reading FDAT input file: 'fwtool2/FDAT_enc.bin' ... cipher method = 2, block length = 1024
Writing FDAT output to 'fwtool2/FDAT_dec.bin' ... decrypt_fdat_image(blocknum=0): block checksum mismatch (expected: 948d, calculated: f847)!
fdat_decrypt_file() returned error!
```

**Comment by ma1co** [comment]
This is the wrong place for your question. You're talking about nex-hack's [fwtool.exe](http://www.personal-view.com/faqs/sony-hack/fwtool). This repository contains a rewrite in python (a completely different program). Ask your question at the [personal-view forum](http://www.personal-view.com/talks/discussion/12756/sony-alpha-hacks-talk).

Note that for 3rd generation firmware, you have to recompile fwtool.exe with my [patch](http://www.personal-view.com/talks/discussion/comment/208911#Comment_208911).
