### ISSUE TITLE
How to modify.TAR verification novice

### ISSUE THREAD

**Issue by 572017317** [ma1co/fwtool.py#13]
I unzip the J1 file through fwtool and replace the J1 file with the ALLLANG file, and then recompress it into the tar file. But I won't modify the verification. Or you can record the method as video and send it to me

**Comment by ma1co** [comment]
Repacking is not supported. Please use [Tweak ](https://github.com/ma1co/OpenMemories-Tweak) instead.

**Comment by 572017317** [comment]
> 不支持重新包装。请改用[Tweak](https://github.com/ma1co/OpenMemories-Tweak)。

But A7R3 doesn't support this

**Comment by ma1co** [comment]
The A7R3 uses new firmware encryption keys. Until these are known, nothing can be done on these cameras (Tweaks are based on fwtool).

**Comment by 572017317** [comment]
> A7R3使用新的固件加密密钥。在知道这些之前，没有什么可以在这些相机上完成（Tweak基于fwtool）。

A6500 A6300 RX100M5 adjustment after the phase opportunity black screen, how to solve this problem?
