### ISSUE TITLE
tried installing open memories: tweak for PJ 680 japanese model but got unknown camera error

### ISSUE THREAD

**Issue by ashishs911** [ma1co/fwtool.py#15]
Please add PJ 680 in the compatible cameras

**Comment by ma1co** [comment]
As a first step, we'd have to dump the AS300 firmware. We'll do this using the firmware update mode. First, we have brute force the model id of your camera. This won't install anything on your device. If you're interested to help, here's what you can do:

* If you're on windows, download the newest development build of pmca-console [here](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts). If you're on os x, you have to wait for the next release (sorry).
* Download [0x61010000.zip](https://github.com/ma1co/Sony-PMCA-RE/files/1738472/0x61010000.zip) and place it in the same folder (no need to unpack). It contains a bunch of firmware images which might match your camera.
* Power on your camera and connect it over USB to your computer.
* Open a command prompt and run the following command: `pmca-console guess_firmware -f 0x61010000.zip`
* With a bit of luck, the script should find the model id of your camera.

Let me know if you need any help.

**Comment by ma1co** [comment]
Sorry for my late reply.
As a first step, we'd have to dump the PJ680 firmware. We'll do this using the firmware update mode. First, we have brute force the model id of your camera. This won't install anything on your device. If you're interested to help, here's what you can do:

* If you're on windows, download the newest development build of pmca-console [here](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts).
* Download [0x61010000.zip](https://github.com/ma1co/Sony-PMCA-RE/files/1738472/0x61010000.zip) and place it in the same folder (no need to unpack). It contains a bunch of firmware images which might match your camera.
* Power on your camera and connect it over USB to your computer.
* Open a command prompt and run the following command: `pmca-console guess_firmware -f 0x61010000.zip`
* With a bit of luck, the script should find the model id of your camera.

Let me know if you need any help.

**Comment by ma1co** [comment]
Closed due to inactivity. @ashishs911 Please reopen if you make progress.
