### ISSUE TITLE
RX0 firmware available.

### ISSUE THREAD

**Issue by mungewell** [ma1co/fwtool.py#20]
I'm a little slow to notice, but there's f/w for the RX0 available now (since Oct 2018).
https://www.sony.ca/en/electronics/cyber-shot-compact-cameras/dsc-rx0-dsc-rx0g

Any use to you?
Simon.

**Comment by ma1co** [comment]
Thanks, the RX0 has already been added to devices.yml some time ago: aefed2c04946c0f86a43d9d4df0a5f1a63f31fca
