### ISSUE TITLE
Gen4 Repacking

### ISSUE THREAD

**Issue by saud-kh** [ma1co/fwtool.py#21]
I was very pleasantly surprised to find you have updated support to include gen4 decrypting. I am just curious though at this stage, is it possible to re-encrypt in future versions? is this feasible or did have things changed with the new gen?

Also, in your experience do you suppose that the swapping the language files (and their sums) would work on the new gen? I've read on forums that method didnt work on gen3 but i wasnt sure if the person trying to do it knew what he was doing.

p.s. I tried the unpacking method on the newly released v5.0 for the a9 and it worked without an issue. it seems they havent changed the encryption code

**Comment by huydexign** [comment]
Yes, it's worked, fwtool can Unpack new firmware version 3.0.1 of A7Riii. Thanks to ma1co so much, but i'm still waiting for a repacking method to repack .dat firmware data file. I have an A7R3 domestic with only Japanese language, i cant change to other languages. The old method with OpenMemories-Tweak not work on new series A7iii & A7Riii. I'm waiting for a long time for a hero guy can hack to active all languages on Japanese domestic Sony A7iii & A7Riii. I need some help, please.

P/s: Follow saud-kh change language in firmware's unpacked here (and thanks to saud-kh so much): https://www.personal-view.com/talks/discussion/21766/guide-sony-a7iiia7riiia9-firmware-language-mod#Item_1

**Comment by haraldt1** [comment]
hello, someone can help you build a language firmware for a7r iii and a7r iv.
i can't do it according to these instructions: https://www.personal-view.com/talks/discussion/21766/guide-sony-a7iiia7riiia9-firmware-language-mod#Item_1

**Comment by ma1co** [comment]
Sadly, repacking gen4 firmware files is not possible. The files include a cryptographic signature and we don't have the private keys. So for now, there is no way to create custom gen4 firmware updates. However, I'm making progress reverse engineering the maintenance mode (senser mode), which seems to be unchanged on the new models. I hope to release this soon.
