### ISSUE TITLE
Support for Sony A7x Mark iii

### ISSUE THREAD

**Issue by SizzGames** [ma1co/fwtool.py#23]
Hello, 

Is there any ETA for the support for a Sony A7x Mark iii? 

If I can grant any help in this process please let me know. 

The model number is: ILCE-7M3
And current Firmware version is : 3.01

The errors that I got while trying to install the Open Memories app and Tweak were: 

> Switching to app install mode
> Traceback (most recent call last):
>   File "<string>", line 73, in do
>   File "pmca\commands\usb.py", line 207, in installCommand
>   File "pmca\commands\usb.py", line 31, in switchToAppInstaller
>   File "pmca\usb\sony.py", line 180, in switchToAppInstaller
>   File "pmca\usb\sony.py", line 147, in _sendCommand
>   File "pmca\usb\sony.py", line 94, in sendSonyExtCommand
>   File "pmca\usb\__init__.py", line 58, in _checkResponse
> Exception: Response code not OK: 0x2006

Kind Regards, 

Iddo

**Comment by ma1co** [comment]
In the latest [development build](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts), tweaks should now be supported for this camera, too. You can use `pmca-console serviceshell` or the "Start tweaking (service mode)" button in the Tweaks tab of pmca-gui. This will require the installation of custom USB [drivers](https://github.com/ma1co/Sony-PMCA-RE#windows-drivers).
