### ISSUE TITLE
Repacking documentation for Gen 2 devices

### ISSUE THREAD

**Issue by c1ko** [ma1co/fwtool.py#31]
Hi, I am trying to modify the firmware of my NEX-5R. Unpacking the firmware / updater will "deeply" unpack all files.
How can I repack an unpacked firmware.tar file?

I am trying to modify files in `firmware.tar_unpacked/0700_part_image/dev/nflasha8_unpacked_unpacked` and I dont see an obvious way to create a firmware.tar file from the various "unpacked" and "unpacked_unpacked" folders that will work. I guess there is a trick somewhere that I do not understand.

My first guess was to simply edit the files in the camera in-place, but the interesting parts of the filesystem are mounted read-only and there seems to be no way to remount using the busybox interface via telnet.

**Comment by c1ko** [comment]
Hi @CyberUSB2 , thanks for pointing that out. Unfortunately, the documentation only talks about "3rd level repacking" but it does not really mention how to do it. I will definitely test the QEMU approach, that seems a lot tidier than messing with the real hardware.
I am still interested in what the "canonical" way of patching individual files on the real camera is, so if someone has a little experience on that I would be glad to hear.

**Comment by CyberUSB2** [comment]
That's great to hear that writing individual files back to the camera is possible! (rather than having to re-pack an entire firmware)

What was the correct commands you gave to successfully write individual files back to the camera?
