### ISSUE TITLE
How about A6400? Thanks.

### ISSUE THREAD

**Issue by Deng-Kowalski** [ma1co/fwtool.py#32]
I found there is support for a6300 and a6500 but not 6400. Will it be an update on 6400? Thanks a lot.

**Comment by ma1co** [comment]
In the latest [development build](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts), tweaks should now be supported for this camera, too. You can use `pmca-console serviceshell` or the "Start tweaking (service mode)" button in the Tweaks tab of pmca-gui. This will require the installation of custom USB [drivers](https://github.com/ma1co/Sony-PMCA-RE#windows-drivers).
