### ISSUE TITLE
Sony a7c

### ISSUE THREAD

**Issue by digitalprojections** [ma1co/fwtool.py#34]
Is it supported?
I can get the camera info.
I need to install international menu with English if supported

**Comment by ma1co** [comment]
In the latest [development build](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts), tweaks should now be supported for this camera, too. You can use `pmca-console serviceshell` or the "Start tweaking (service mode)" button in the Tweaks tab of pmca-gui. This will require the installation of custom USB [drivers](https://github.com/ma1co/Sony-PMCA-RE#windows-drivers).
