### ISSUE TITLE
I also purchased a Sony ZV-E10 from Japan and need to get it unlocked to English. I tried the link, it opened, but I can’t read Chinese. It looks like there is a login screen that pops up. Where can I turn to for help with this?

### ISSUE THREAD

**Issue by coho4259** [ma1co/fwtool.py#37]

**Comment by ma1co** [comment]
In the latest [development build](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts), tweaks should now be supported for this camera, too. You can use `pmca-console serviceshell` or the "Start tweaking (service mode)" button in the Tweaks tab of pmca-gui. This will require the installation of custom USB [drivers](https://github.com/ma1co/Sony-PMCA-RE#windows-drivers).
