### ISSUE TITLE
sony a1 a7c a7m3 a7r3 a7m4 a7r4 fx3 ZV-E10 ZV1 A6100 A6400 A6600 RX100M6 RX100M7 Unlock English on Japanese, language change

### ISSUE THREAD

**Issue by Camerasupport** [ma1co/fwtool.py#38]
This is a legitimate service ,Professional technology and a lot of experience

There is a fee for the service. Dealers please do not contact me, it is not legal to smuggle cameras.  We only provide services to individual users.

One person can do up to 2 cameras at the same time.  If there are more than 2 pieces, we need to verify that your camera is for personal use and not for commercial sale.

English mail customer service 👨🏻‍💻
wanghaixian1995@gmail.com 

Chinese Taobao customer service 👨🏻‍💻
https://m.tb.cn/h.fJAy0ya

💻Remotely, you need to prepare:  
computer (Windows✅ macOS✅ Linux✅)
Install remote software (TeamViewer)
  USB cable 
high speed internet

💬Customer FAQs:
Need to mail the camera or disassemble it?
No need to mail, no need to disassemble, we remotely authorize the language through the computer and link to the computer through a USB cable.

Is there a risk?  Does it affect the camera?
100% success, zero risk, just add language.  Does not affect other functions of the camera.

Will updating the firmware or resetting the camera language go away?
Firmware can be upgraded, system can be reset, language doesn't disappear, it's permanent

How long does it take to add a language?
Windows 10 minutes
Linux 10 minutes
MacOS 20 minutes

**Comment by piterzc** [comment]
I try u locking my ZV E10 bu it didn't work 
I neen help

**Comment by piterzc** [comment]
I try u locking my ZV E10 bu it didn't work
I neen help @ma1co
