### ISSUE TITLE
Question Regarding Firmware.dat

### ISSUE THREAD

**Issue by pqhf5kd** [ma1co/fwtool.py#4]
I'm on macOS High Sierra and Sony haven't provided a way to update the OG A7 series on Sierra/High Sierra.
Can I use the firmware.dat extracted with this tool from Update_ILCE7V320.exe and the pica-gui-v0.13-osx app to update my A7?

**Comment by ma1co** [comment]
I'm not sure if the mass storage drivers work on Sierra (firmware update is always in mass storage mode). See [this note](https://github.com/ma1co/Sony-PMCA-RE#os-x-drivers) (it is also valid for firmware updates).

So the first thing to try is to switch your camera to mass storage mode and try the info command. If this works, the firmware update probably works, too.

**Comment by pqhf5kd** [comment]
No, it appears they don't work.
`Exception: Mass storage error: Sense 0x2 0xff 0xff`

FW updates can't be done over MTP like app installs.

Looks like I need to find a Windows machine.
