### ISSUE TITLE
devices.yml - missing some camera defs

### ISSUE THREAD

**Issue by mungewell** [ma1co/fwtool.py#7]
At a glance the following cameras are missing from 'devices.yml'.

HDR-AS20
HDR-AS200V
HDR-AS50
HDR-AS300

**Comment by ma1co** [comment]
Correct, this is because there are no firmware updates available for these cameras, so the model number has to be guessed / brute forced. If anybody owns one of these cameras, please contact me.

**Comment by ma1co** [comment]
@tajson 
Thank you very much, the AS200 is now supported in updatershell.

The next step is to dump the firmware. Here's how to do that:

* Download the newest development build of pmca-console [here](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts).
* Run `pmca-console updatershell`
* Run the following updatershell command to dump the firmware: `pull /dev/nflasha`
* Run the following updatershell command to dump the bootloader partitions: `bootloader`
* Run the following updatershell command to reboot your camera back to normal mode: `exit`
* You should now have files called `nflasha` and `boot1` to `boot5` on your computer. Please zip them and upload the file to my [dropbox](https://www.dropbox.com/request/WXQ1IKIoPo4ECK8CFxRx).

Thank you for your help!

**Comment by tajson** [comment]
@ma1co: Done

**Comment by ma1co** [comment]
@tajson 
Thanks, that was very quick.

I'm currently trying to understand how the display works on the old action cams. To install run android apps, we have to replace the live streaming app by our custom app. Here's how to do that:

* Download the newest windows development build of pmca-console [here](https://ci.appveyor.com/project/ma1co/sony-pmca-re/build/artifacts)
* Download [sublcd-1.zip](https://github.com/ma1co/fwtool.py/files/1948797/sublcd-1.zip) and unzip it.
* Run `pmca-console updatershell`
* Install the apk: `install sublcd-1.apk`
* Enable usb app installation: `tweak`, then select the corresponding item and `0` to exit
* Exit the updater mode: `exit`
* Configure the Ustream settings as described [here](http://helpguide.sony.net/cam/1520/v1/en/contents/TP0000681079.html) (sorry, you need a Ustream account for now)
* Switch the camera to live streaming mode
* Press record
* The app should open and display "HELLO". You can use the arrow keys to cycle through 7 different test messages. Please report what is shown.

Please let me know if you need any help. It is possible that some of the described steps may not work. It is some early development that we are doing here :)

**Comment by mungewell** [comment]
> I'm currently trying to understand how the display works on the old action cams.

By display do you mean the HDMI output (ie to TV) or the LCD panel on the side of the unit? If you mean the later, a hint might be the 'view*.uxc' files which appear to be a definition on how the menus work.

Which cameras might the above APK work on? (I have AS15 and AS100).

BTW didn't we figure out how to pull/push/adjust the Ustream settings in via pcma-console. ;-)
https://github.com/ma1co/Sony-PMCA-RE/pull/53

You might be able to get by with fake credentials (ie not actually need a Ustream account), that would normally be validated by the official PC configure process.

**Comment by ma1co** [comment]
@tajson Did you run `install sublcd-1.apk` in updatershell? The "WAIT" message is probably coming from the internal app that we're trying to replace.

**Comment by tajson** [comment]
@ma1co I resetted the camera, and redid all steps.

The screen blanks when activating live-mode (does not display "HELLO"), but I can cycle through the test messages.
Test messages, by pressing "next", in order or apperance:

> FAST
(blinking)

> ON

> VERYL

> INFO

> 1280
> INFO

> 1280 ō67
> INFO

> 1280 ō67
> HELLO
("HELLO" blinking slowly)

As soon as the top row is displaying "1280" and/or "ō67", it never disappears.

**Comment by ma1co** [comment]
@tajson Thanks for testing and reporting!

Here is another apk: [sublcd-2.zip](https://github.com/ma1co/fwtool.py/files/1968699/sublcd-2.zip) (unzip it). You should be able to install it using `pmca-console install -f sublcd-2.apk`. If this doesn't work, use updatershell again.

This app should now show the names of the installed apps ("Application", "PlayMemories Camera Apps", "Application Management", etc). You should be able to navigate between the apps using the arrow keys.

Please let me know if this works.

**Comment by ma1co** [comment]
@tajson Thanks for testing, I have pushed the changes to the [repository](https://github.com/ma1co/OpenMemories-Launcher).

Pressing the record button should launch the selected app. The pre-installed apps are probably not optimized for action cams (as they are not accessible during normal operation). So my guess is that the screen just turns blank and the camera hangs. Can you confirm this?

**Comment by tajson** [comment]
@ma1co

"**Application management**" displays "NONE", then the camera is unresponsive.
"**Smart Remote Control**" displays "NONE" and returns to the cameras main menu.
"**Highlight Movie Maker**" displays "NONE", then "WAIT", then "EDIT". Any further interactivity seems to crash the application.
"**PlayMemories Camera Apps**" displays "NONE", then the camera is unresponsive.

**Comment by ma1co** [comment]
@tajson I have another version for you to test: [sublcd-3.zip](https://github.com/ma1co/fwtool.py/files/1968895/sublcd-3.zip). Does this one show "NONE" as well when launching the apps?

**Comment by tajson** [comment]
@ma1co:  Display goes blank, then the camera is unresponsive.
Note: Not on all applications though, some goes back to the main menu etc.

**Comment by ma1co** [comment]
@tajson What happens for the Highlight Movie Maker? Blank - "WAIT" - "EDIT"?

**Comment by tajson** [comment]
@ma1co: Correct. blank screen -> "WAIT" -> "EDIT"
Pressing prev/next produces "WAIT" -> "LIVE"-menu (back to the camera).

**Comment by mungewell** [comment]
Kinda repeating my questions from above... :-)
1). Which cameras will/should this APK work on? Willing to test with the ones I have.
2). It's now clear that the display you are talking about is the LCD, however anyone thinking to look at the ActionCam's HDMI output to see if the apps are rendering content there?

**Comment by ma1co** [comment]
I have [released](https://github.com/ma1co/OpenMemories-Launcher/releases/latest) version 2.0 of the launcher app (same code as sublcd-3.apk). It should support the AS100, AS200, AS300, X1000, X3000 plus recent CX / PJ cameras (see the [list](https://github.com/ma1co/OpenMemories-Framework/blob/master/docs/Cameras.md) for more information). The AS50 should be supported as soon as someone dumps its firmware. Supporting the AZ1 / QX cameras is difficult as the lcd screens are really limited.

@mungewell Feel free to test it. Keep in mind that the app will replace the integrated ustream app. You won't be able to stream video anymore. You should be able to uninstall everything by running `shell rm /mnt/app/*.apk`, `shell rm /mnt/backup/*.bak` and `exit` inside updatershell. This should reset all android apps and settings.

I've never tried running any app over HDMI. If you have time, please try and report what happens.
